### ISSUE TITLE
Create backup 

### ISSUE THREAD

**Issue by glacierbits** [trezor/trezor-suite#1116]
**Invision** [here](https://projects.invisionapp.com/share/D9VLEHKSUEN#/screens/401149053)

**Comment by bosomt** [comment]
backup is broken for 1.8.4 and 2.2.0 and 2.3.0 FW 
works fine with 1..8.3

**Comment by sorooris** [comment]
@bosomt please specify _steps to reproduce_ and _actual behavior_.

**Comment by bosomt** [comment]
works fine now with 1.9.0
i will test it with 2.3.0

**Comment by wendys-cats** [comment]
**Issue: Suite does not register device has been disconnected during backup**

**Steps to reproduce:**
1. Connect a T1 device with backup
2. Connect a TT device without backup, go into device settings
3. Check the backup boxes for TT device and disconnect it
4. Continue with the backup process

**Expected behaviour:**
Suite will detect that device has been disconnected. 

**Actual behaviour:**
Console shows session has no been found, but Suite does not send a warning to the user about it, and this will result in Suite attempting to initialize a backup for any other connected device. All three videos show the same exact scenario. 
IF the other connected device is a T1 model, it will result in about 7-10 minutes period where the device shows only "Processing, Please wait" (photo below). It does not hinder the device's funcionality, it will disappear after any action that requires a screen message. 
videos:
https://drive.google.com/file/d/1V6o9wh7mBmo0PymGxpZLhPGKU5dV5l1w/view
https://drive.google.com/file/d/1CANvRxGszxZhxstg-WSyCTSVCrWScWGk/view
https://drive.google.com/file/d/1w9WdyMbInfDhCE5pvIAGnXed7FlNPDDm/view

![T1 processing](https://user-images.githubusercontent.com/58593111/78886664-e70b1880-7a5e-11ea-80f8-101a21f9011b.jpg)

**Comment by mroz22** [comment]
Nice catch! It's rather edge case, but still should be fixed. On it.

**Comment by wendys-cats** [comment]
**Issue persists with Remembered wallet.**

**Steps to reproduce:**
**1.** Connect a T1 device with backup
**2.** Connect a TT device without backup
**3.** Choose the TT wallet, click Remember wallet
**4.** In Device settings, initialize Create Backup
**5.** Check the backup boxes for TT device and disconnect it
**6.** Continue with the backup process

**Expected behaviour:**
Suite will detect that device has been disconnected, just as it does when wallet of the disconnected device is not remembered.

**Actual behaviour:**
Console shows session has no been found, but Suite does not send a warning to the user about it. After attempting to continue with backup proccess, Suite will show an error message - "Backup failed, Seed already backed up".

IF the other connected device is a T1 model, it will result in about 7-10 minutes period where the device shows only "Processing, Please wait" (photo below). It does not hinder the device's funcionality, it will disappear after any action that requires a screen message.

**Comment by wendys-cats** [comment]
**Issue: "Your Trezor wallet is not backed up. Create backup" allows to start backup of a disconnected device.**

**Steps to reproduce:**
**1.** Connect a T1 device with backup
**2.** Connect a TT device without backup
**3.** Choose the TT wallet, click Remember wallet
**5.** Disconnect the TT device
**6.** Click the red alert message Create Backup

**Expected behaviour:**
Suite will detect that device has been disconnected, just as it does when wallet of the disconnected device is not remembered. The red alert message should behave the same way as Create backup button in Device Settings does - be disabled, or hidden completely once Suite detects the device has been disconnected. 

**Actual behaviour:**
After attempting backup proccess, Suite will show an error message - "Backup failed, Seed already backed up".

IF the other connected device is a T1 model, it will result in about 7-10 minutes period where the device shows only "Processing, Please wait" (photo below). It does not hinder the device's funcionality, it will disappear after any action that requires a screen message.

**video:** https://drive.google.com/file/d/1abl1zai4KD8jBvTTOkAf4IlEYrkcCDLY/view

**Comment by wendys-cats** [comment]
**Issue: Suite does not register device has been disconnected during backup persists with Remebered wallet**

**Steps to reproduce:**
**1.** Connect a T1 device with backup
**2.** Connect a TT device without backup
**3.** Choose the TT wallet, click Remember wallet
**4.** In Device settings, initialize Create Backup
**5.** Check the backup boxes for TT device and disconnect it
**6.** Continue with the backup process

**Expected behaviour:**
Suite will detect that device has been disconnected, just as it does when wallet of the disconnected device is not remembered.

**Actual behaviour:**
Console shows session has no been found, but Suite does not send a warning to the user about it. After attempting to continue with backup proccess, Suite will show an error message - "Backup failed, Seed already backed up".

IF the other connected device is a T1 model, it will result in about 7-10 minutes period where the device shows only "Processing, Please wait" (photo below). It does not hinder the device's funcionality, it will disappear after any action that requires a screen message.

**video:** https://drive.google.com/file/d/1fxQGx_BANJcJ7f80es64S2cqjUJ1gYtK/view

**Comment by wendys-cats** [comment]
**Issue: "Your Trezor wallet is not backed up. Create backup" allows to start backup of a disconnected device persists**

**Steps to reproduce:**
**1.** Connect a T1 device with backup
**2.** Connect a TT device without backup
**3.** Choose the TT wallet, click Remember wallet
**5.** Disconnect the TT device
**6.** Click the red alert message Create Backup

**Expected behaviour:**
Suite will detect that device has been disconnected, just as it does when wallet of the disconnected device is not remembered. The red alert message should behave the same way as Create backup button in Device Settings does - be disabled, or hidden completely once Suite detects the device has been disconnected.

**Actual behaviour:**
After attempting backup proccess, Suite will show an error message - "Backup failed, Seed already backed up".

IF the other connected device is a T1 model, it will result in about 7-10 minutes period where the device shows only "Processing, Please wait" (photo below). It does not hinder the device's funcionality, it will disappear after any action that requires a screen message.

**video:** https://drive.google.com/file/d/1aJyKLEFA92WPAT2kZQwl-MUAmIpMnV8_/view

**Comment by wendys-cats** [comment]
**QA OK**

**Tested with**
**OS** nixos
**Browser** Chromium Version 83.0.4103.61 (Developer Build) (64-bit)
**Suite URL** suite-web/develop version 20.6.1-beta
**Device** TT 2.3.1 FW and T1 1.9.1 FW

Suite asks to reconnect the device when trying to start a back up of a disconnected device. Very nice.

**Comment by sorooris** [comment]
Suite version: suite-web/develop version 20.6.1-beta 9d2fa6fef4e4dbb5f54d9eefa5c84388f11ed5cb
