### ISSUE TITLE
Fees adjustment in Send flow/Suite side

### ISSUE THREAD

**Issue by MiroslavProchazka** [trezor/trezor-suite#11666]
Adjust the fees option in Send flow based on the following description: 

Low fee - remove completely 
Economy fee - rename to Low fee 
Medium fee - stays the same
High fee - stays the same
Custom fee - stays the same 

Align the buttons after the change accordingly.

Investigate whether we need to do the changes just in wallet-core, or also in connect.

**Comment by MiroslavProchazka** [comment]
cc @Hannsek @sime @Hermez-cz - please comment/adjust the description according to your thoughts. Thx!

**Comment by komret** [comment]
Resolved by https://github.com/trezor/trezor-suite/pull/11733

**Comment by bosomt** [comment]
LOW is still present in Send and in trade section.
If expected please approve

![Image](https://github.com/trezor/trezor-suite/assets/31506317/bc7674cc-a3e7-478c-b4fe-28766e381c71)



![Image](https://github.com/trezor/trezor-suite/assets/31506317/44ee28e7-103b-46d3-86ca-fc85ef3dbc86)


**Info:**
 - Suite version: desktop 24.6.1 (ee1bf19e747daba31bec272b64d09bfa8c6a807e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/24.6.1 Chrome/118.0.5993.159 Electron/27.3.8 Safari/537.36
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.7.1 regular (revision 83d1ce2b8e6e4eefe09539f06b28709c8a7a89dc)
 - Transport: BridgeTransport 2.0.33

**Comment by MiroslavProchazka** [comment]
> Low fee - remove completely
> Economy fee - rename to Low fee

thats expected,
