### ISSUE TITLE
Not able to change device settings without starting discovery when already different remembered device

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#13154]
**Describe the bug**
Not able to change device settings without starting discovery when already different remembered device.

**Steps to reproduce:**
1. Connect device 1
2. Remember it
3. Connect device 2
4. Try to change device or coins settings without starting discovery of device

**Info:**
 - Suite version: web 24.8.0 (a9756f258bd2747a2ec817fb796eaa4688f6e456)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T3T1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33

**Screenshots:**

Uploading Screen Recording 2024-07-03 at 9.06.13.mov…

**Comment by MiroslavProchazka** [comment]
@bosomt can you re-upload the video please?

**Comment by bosomt** [comment]
Maybe we can consider adding settings button for every connected device ?

https://github.com/trezor/trezor-suite/assets/31506317/73b41c6a-d96c-4f86-bdfb-5edd80d51946

**Comment by MiroslavProchazka** [comment]
@bosomt Can you try one more time on develop? SHould be fixed

**Comment by jvaclavik** [comment]
I think we fixed this issue in this PR: https://github.com/trezor/trezor-suite/pull/13199

@bosomt Could you please test it once again from current develop? 🙏

**Comment by bosomt** [comment]
im still not able to access device settings before discovery when there is already remembered device present

https://github.com/trezor/trezor-suite/assets/31506317/e5734d43-73a9-48e8-af74-b73843788b5d

**Info:**
 - Suite version: web 24.8.0 (814ab5d0df52939057bfa7643e7c0a83012e86f7)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:127.0) Gecko/20100101 Firefox/127.0
 - OS: MacIntel
 - Screen: 1512x982
 - Device: Trezor T2B1 2.8.0 regular (revision dd4671a5104952ef505d28d1f9e94d1484b4607a)
 - Transport: BridgeTransport 2.0.33

**Comment by MiroslavProchazka** [comment]
cc @jvaclavik we need to fix this until 24.7 production release

**Comment by pavelmario** [comment]
we've discussed this issue w/ @jvaclavik and agreed on closing this issue
