### ISSUE TITLE
TrendTicker component missing loading and 0% change, it shows -

### ISSUE THREAD

**Issue by tomasklim** [trezor/trezor-suite#16127]
**Describe the bug**

This component shows trend only if it differs from `0` (stable can have same rate one week later)

This component does not show loading state. It uses `Fiatvalue` component but `showLoadingSkeleton` uses `currentRate` and not both `lastWeekRate` and `currentRate`

![Screenshot 2025-01-01 at 17 22 14](https://github.com/user-attachments/assets/63bbc9c0-b2bf-44e4-b54c-5dca726e328b)

**Comment by tomasklim** [comment]
@vojtatranta was this fixed by your fix of fiats for tokens?

**Comment by vojtatranta** [comment]
> [@vojtatranta](https://github.com/vojtatranta) was this fixed by your fix of fiats for tokens?

Not for this case, I was fixing the token value in the sidebar, I am looking into this now.

**Comment by vojtatranta** [comment]
> [@vojtatranta](https://github.com/vojtatranta) was this fixed by your fix of fiats for tokens?

Yeah, I rechecked it and it does show loading skeleton even when the value is 0, so it seems to be correct. Though, not fixed by me.

**Comment by EuryShadow** [comment]
**QA OK**

<img width="2402" height="1402" alt="Image" src="https://github.com/user-attachments/assets/9ce4da03-c930-47bb-b549-b4a542dbe535" />

**Info:**
 - Suite version: desktop 26.7.0 (51c3928dd8d2865b6dface418c5b1134e4d49467)
 - Browser: Trezor Suite 26.7.0
 - OS: MacIntel
 - Screen: 1710x1112
 - Device: Trezor T3T1 2.12.1 universal (revision 64698d0d844e3322eca435beaae3df602aa08b10)
 - Transport: BluetoothTransport, BridgeTransport 3.2.1
