### ISSUE TITLE
redirect loop while fetching 404.html (only in sldev)

### ISSUE THREAD

**Issue by slowbackspace** [trezor/trezor-suite#1646]
<img width="847" alt="Screenshot 2020-04-28 at 15 58 01" src="https://user-images.githubusercontent.com/6961901/80496141-0fed4200-8969-11ea-8fa3-e114c60da762.png">

**Comment by slowbackspace** [comment]
for now I blame adminkos, because nginx returns 302 redirection with location header `develop/404.html` and then same thing all over again till chrome stops running in circle. but I can't verify it since staging doesn't work for me!!!

(it could also simply be a change in nextjs, I am tired)

**Comment by vladimirvolek** [comment]
Fixed now!

**Comment by slowbackspace** [comment]
still happening on sldev, staging seems ok but maybe just because 404 page is not properly set-up 🤷 

<img width="1390" alt="Screenshot 2020-05-21 at 16 14 43" src="https://user-images.githubusercontent.com/6961901/82567809-31170c00-9b7e-11ea-991e-4a44dd115c16.png">

**Comment by szymonlesisz** [comment]
should be fixed now, it was nginx configuration like @slowbackspace suspect
