### ISSUE TITLE
Layout shift on CreateWalletLoadingScreen

### ISSUE THREAD

**Issue by yanascz** [trezor/trezor-suite#19361]
When shown for the first time, the layout of the screen shifts before navigating to the next screen.

https://github.com/user-attachments/assets/2ae7b102-93a7-42d2-9229-6c7a2c7ab1d4

**Comment by BrantalikP** [comment]
rely on https://github.com/trezor/trezor-suite/issues/19098 should be fixed afterwards

**Comment by matejkriz** [comment]
Let's try to find some quick solution, if not possible to fix it quickly, let's wait for New Architecture (and new reanimated)

**Comment by honzauher** [comment]
**QA NOK**

Still happening but it's barely noticable

**Info:**
- develop -25.9.1, commit 57533c
- OS: Android

**Comment by BrantalikP** [comment]
@yanascz Have we moved this to QA intentionally? I cannot see any PR related to this issue.

If not, I will move it after the period the new architecture is integrated. Thanks

**Comment by zako05** [comment]
QA OK ✅

https://github.com/user-attachments/assets/7fc7cc46-e8c9-4f97-a070-6c6074f5ed51
