### ISSUE TITLE
Incorrect validation when fee number is invalid

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#2202]
**Info:**
 - OS: nixos
 - Browser: Chromium Version 83.0.4103.61 (Developer Build) (64-bit)
 - Suite web, commit 44254ee8780ea1550b017621c154b2990b1fe3f0
 - Firmware Version: model 2.3.2 63ebb8ccb
 
**Describe the bug**
When entering invalid fee on Send page in number-decimal point-number format (f.e. 1.0), Suite will react with "Not enough funds" error notification instead of an error about invalid fee. 

**Steps to reproduce:**
1. Open Send page
2. Change fee to invalid format of number-decimal point-number (f.e. 1.0)

**Expected result:**
Suite will show the same error notification as Wallet - "Fee is not a natural number."

**Actual result:**
Instead of error notification about invalid fee, Suite shows "Not enough funds"

**Screenshots:**

                                     

                                    Wallet

![image](https://user-images.githubusercontent.com/58593111/89885209-ff38a300-dbca-11ea-84f2-68a9b0afa5d1.png)

                                     Suite 
![image](https://user-images.githubusercontent.com/58593111/89885277-1b3c4480-dbcb-11ea-8111-ba72025e1bec.png)

**Comment by bosomt** [comment]
maybe you can add some field size limitations to send dialogue too ?

![image](https://user-images.githubusercontent.com/31506317/89889524-08793e00-dbd2-11ea-93cd-18664b13a1dc.png)

**Comment by szymonlesisz** [comment]
- first issue should be solved by new send form
- sencon issue (input max length) should be solved by https://github.com/trezor/trezor-suite/pull/2301

**Comment by wendys-cats** [comment]
**QA NOK**
Issue with incorrect validation still persists, tested [here](https://staging-wallet.trezor.io/). commit hash 118b1cb4d9f9c8aed2634010fe64a02f66385539

                                                   Screenshots
                            
![image](https://user-images.githubusercontent.com/58593111/92243351-a9050a00-eec1-11ea-8995-6580bb731ca2.png)

![image](https://user-images.githubusercontent.com/58593111/92245568-dbfccd00-eec4-11ea-87d0-9b8484c2bb8c.png)

**Comment by sorooris** [comment]
**QA NOK**
Issue seems to be strangely specific only to an even number of decimal **zeroes** and "**1.**" (not odd number of zeroes).

> Wallet Version: web, 20.9.1 cf1f180
OS: NixOS
Browser: any supported (tested Firefox 79.0 + Chromium 84.0.4147.125)
Device: T1 1.9.3 0d5f00668

1) **incorrect error message** ("Not enough funds") is displayed when an **even** number of zeroes is in the feePerUnit field present
2) **Send transaction button** stays disabled when an **odd** number of zeroes is in the feePerUnit field present
___
No error message displayed, validated _incorrect_ successfully.
**"1." sat/B**
> ![image](https://user-images.githubusercontent.com/10185314/92493328-ab829f00-f1f4-11ea-9825-bb2d79305fc7.png)

**Incorrect** error message displayed.
**"2.00" sat/B**
> ![image](https://user-images.githubusercontent.com/10185314/92495971-d3bfcd00-f1f7-11ea-9951-64f115011250.png)

Any other number in decimals is validated as "not an integer" **correctly**.
> ![image](https://user-images.githubusercontent.com/10185314/92494012-788cdb00-f1f5-11ea-98db-eeed7626e9af.png)

However, leaving the decimals incorrectly validated in the feePerUnit field also displays the incorrect error message "Not enough funds" under the _outputs[0].amount_ and _outputs[0].fiat_ fields, even when they are  filled out correctly and the account has enough funds.
> ![image](https://user-images.githubusercontent.com/10185314/92494517-184a6900-f1f6-11ea-919f-c45760f942e9.png)

Furthmore, deleting a zero from an even number of zeroes validates all fields as correct but does not enable the _Send transaction_ button.
> ![image](https://user-images.githubusercontent.com/10185314/92495048-ba6a5100-f1f6-11ea-8147-dde9e565a846.png)

**Comment by sorooris** [comment]
**QA OK**

> Wallet Version: web, 20.9.1 e243afdb73e35fa08f39a7fc08a28b84baa3ac58
OS: NixOS
Browser: any supported (tested Firefox 79.0)
Device: Model T 2.3.3 0d5f00668

Could not reproduce.
