### ISSUE TITLE
Send flow - Dark Mode Confirmation Screen, Incorrect Highlighting

### ISSUE THREAD

**Issue by fang314** [trezor/trezor-suite#22113]
**Summary**
On the confirmation screen in dark mode, after confirming the recipient address, the app continues to highlight the address section, even though the user should now be reviewing the amount and fee fields. This leads to confusion, as the user's attention is naturally drawn to the highlighted section instead of the next important step—reviewing the transaction amount and fee.

**Steps to Reproduce**
1. Initiate a transaction in the app
2. Go to the confirmation screen in dark mode.
3. The 'Recipient address' section remains highlighted

**Expected Behavior**
After confirming the address, the 'Address' box should be darkened or de-emphasized. The amount and fee sections should be the primary visual focus for the user, guiding their attention to the most relevant fields needed for confirmation

[Slack for ref](https://satoshilabs.slack.com/archives/C03FL9TCURZ/p1759398077481919)

**Comment by tomasklim** [comment]
@EuryShadow could you please check? maybe it is fixed, if not add screenshots/better info. thx!

**Comment by EuryShadow** [comment]
Issue with color palette in dark mode, still present @shenkys 

https://github.com/user-attachments/assets/fbc51a05-33ad-454b-85a7-61fab9662306

develop-26.2.1, commit aac624a720db6029a467d4ca22529927ca9bec46
