### ISSUE TITLE
Implement Unified settigs for Labeling

### ISSUE THREAD

**Issue by peter-sanderson** [trezor/trezor-suite#22543]
| mobile | | desktop |
| --- | --- | --- |
| <img width="390" height="901" alt="Image" src="https://github.com/user-attachments/assets/35322f4c-b618-493e-9e78-c7fef664d9de" /> | <img width="390" height="844" alt="Image" src="https://github.com/user-attachments/assets/32507c3b-5f26-4377-bcbe-8ffa1ed3603f" /> | <img width="1440" height="1024" alt="Image" src="https://github.com/user-attachments/assets/465d2cf2-b312-4082-a8be-3756db3206f5" /> |

- Default is `off` but it can be triggered by click on any `add label` button.
- [Figma](https://www.figma.com/design/0hCYrAdbrnqZzwEDtv59ol/Secure-sync--Evolu-?node-id=6470-59570&t=RS2K9ZjoiZoFwIZO-4)

**Comment by peter-sanderson** [comment]
# QA

- In debug you enable Evolu Labeling
- In Application settings you then see that Labeling has 3 options
- It allows switching from Evolu and Legacy labeling back and forth

On production builds, Evolu is broken (but it works on web), but switching back and forth and test that old labeling (Dropbox, Google, .. is not borken can be done.

**Comment by honzauher** [comment]
QA OK with notes @peter-sanderson 

Switching back and forth works, old labeling works too, but not sure what this TR_LABELING message is:

<img width="882" height="145" alt="Image" src="https://github.com/user-attachments/assets/59d44fa0-1e80-4522-8f74-64f5f54f270f" />


Also theres no labeling setting on mobile yet? 

**Info:**
 - Suite version: desktop 25.11.0 (c9ed8962b18ed2a58b6feff883d960b4d36f57c0)
 - Browser: Trezor Suite 25.11.0
 - OS: MacIntel
 - Screen: 1470x956
 - Device: Trezor T3W1 2.9.4 universal (revision a491f75ab1603d536048fd2cb44ff147ff406b9f)
 - Transport: BridgeTransport 3.1.0, BluetoothTransport

**Comment by OriginalEveres** [comment]
@honzauher TR_LABELING message is fixed, its merged in develop

https://github.com/trezor/trezor-suite/pull/22959 - this is PR for the mobile part fyi

**Comment by honzauher** [comment]
QA OK on desktop

**Info:**
 - Suite version: web 25.11.0 (1ea551f59d620e54c0546ddefd18d1bb14995650)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/142.0.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1920x1080
 - Device: Trezor T3W1 2.9.3 universal (revision 0bd923c78990d8d58f82fe18660e57399aafc0f1)
 - Transport: WebUsbTransport

**Comment by STew790** [comment]
Unfortunately, the TR_LABELING message is still present on latest RC. 
@OriginalEveres 

<img width="1860" height="1039" alt="Image" src="https://github.com/user-attachments/assets/338657be-dd88-4216-99dc-a06be79d999d" />

**Info:**
 - Suite version: desktop 25.11.1 (42adf3d5ec1be5f0918b107c359fb177a91fafa9)
 - Browser: Trezor Suite 25.11.1
 - OS: MacIntel
 - Screen: 3440x1440
 - Device: Trezor T3T1 2.9.4 universal (revision a491f75ab1603d536048fd2cb44ff147ff406b9f)
 - Transport: BridgeTransport 3.1.0, BluetoothTransport

**Comment by komret** [comment]
This has been fixed, closing.

**Comment by honzauher** [comment]
~~QA OK~~

**Info:**
 - Suite version: desktop 25.11.3 (11f396b1f4b8f6833fc69c064774bc5a04138e48)
 - Browser: Trezor Suite 25.11.3
 - OS: MacIntel
 - Screen: 1470x956
 - Device: Trezor T3W1 2.9.5 universal (revision aecac16bb1261988d146079e9ab235056cee422e)
 - Transport: BluetoothTransport, BridgeTransport 3.1.0

**Comment by Ondra-Zik** [comment]
QA NOK

<img width="1240" height="278" alt="Image" src="https://github.com/user-attachments/assets/17d9412a-6a92-4217-8b20-199325b711f6" />

**Comment by honzauher** [comment]
**QA OK** on [2nd RC](https://github.com/trezor/trezor-suite/commit/cdf4b94a863c65de538edc996580efaf155ebd47) (finally) 🙃 

<img width="1174" height="236" alt="Image" src="https://github.com/user-attachments/assets/950e9418-c4f8-468d-bbbc-137a13ac2727" />

**Info:**
 - Suite version: desktop 25.12.1 (cdf4b94a863c65de538edc996580efaf155ebd47)
 - Browser: Trezor Suite 25.12.1
 - OS: MacIntel
 - Screen: 1470x956
 - Device: Trezor T3W1 2.9.6 universal (revision dbb7b00ce10fb7eab33fa2021c4096c623b0b146)
 - Transport: BluetoothTransport, BridgeTransport 3.1.0
