### ISSUE TITLE
Desktop app: Tor connection issues

### ISSUE THREAD

**Issue by szymonlesisz** [trezor/trezor-suite#2876]
**Describe the bug**
discovery with enabled TOR always ends up with an error (works like a charm with disabled TOR)

**Info:**
 - Suite Version: desktop app, 1188894
 - OS: Windows 10
 - Firmware Version: any 

**Screenshots:**
![tor-discovery-error](https://user-images.githubusercontent.com/3435913/98128026-aae64c00-1eb7-11eb-8ccd-715be4115f73.jpg)

![tor-ws-connection](https://user-images.githubusercontent.com/3435913/98145968-85fbd400-1ecb-11eb-8178-31e241c4ce6f.jpg)

**Comment by keraf** [comment]
Looks like a dev build only issue. Can someone from QA confirm please?

**Comment by prusnak** [comment]
What does http://127.0.0.1:9050/ show in your browser?

Does it show: **This is a SOCKs proxy, not an HTTP proxy.** - meaning the Tor is running?

**Comment by mroz22** [comment]
This happens to me running desktop version in dev setup. Broser shows "This site can’t be reached. ERR_CONNECTION_REFUSED" (http://127.0.0.1:9050/)

**Comment by prusnak** [comment]
> This happens to me running desktop version in dev setup.

This is fixed in https://github.com/trezor/trezor-suite/pull/2890

**Comment by szymonlesisz** [comment]
reopening, still happening on fresh artifacts from the develop 491f31e 

1. start app without tor, do first discovery (discovery success)
2. enable tor
3. add hidden wallet and do second discovery (discovery fails, caused by ws connection errors)
4. disable tor and hit "retry" (discovery success)

tor.exe is up and running as a subprocess of Trezor Suite during step 2 and 3
i can access http://127.0.0.1:9050/  and see "This is a SOCKs proxy" message

**Comment by wendys-cats** [comment]
@szymonlesisz tried step by step (even toggled tor on mid-discovery). No discovery error.

Cannot reproduce (but will try further on the newest build)

OS Windows 10 home
suite APP 20.11.1 11888946531d3bf641d83bdbfddae8e0143b0738
device TT 2.3.4

http://127.0.0.1:9050/ says "This is a SOCKs proxy, not an HTTP proxy." I can see tor running as a background process.

**Comment by wendys-cats** [comment]
@szymonlesisz reproduced on fourth attempt. After hitting retry, everything loads properly.

OS Windows 10 home
suite APP 20.11.1 491f31ee27067b57e273e79cd1a6e1cad91459bb
device TT 2.3.4 public
http://127.0.0.1:9050/ says "This is a SOCKs proxy, not an HTTP proxy." I can see tor running as a background process.


![photo_2020-11-05_20-17-15](https://user-images.githubusercontent.com/58593111/98286222-f1b17000-1fa3-11eb-9199-ad6fc91d5cbb.jpg)

**Comment by wendys-cats** [comment]
reporting similar issue

When network is throttle to Slow 3G and user repeatedly turns TOR on and off, Accounts tab will show "Backend is diconnect" and eventually console will return request 429 (too many requests). Since getting back 429, no request has appear (it has been around 10 minutes of wait) and Accounts still show "Connecting". But Dashboard does not say "Discover error".
http://127.0.0.1:9050/ cannot be reach.

OS Windows 10 home
suite APP 20.11.1 491f31e
device TT 2.3.4 public

Steps to reproduce:
1. Throttle network to Slow 3G
2. Turn TOR off/on during first discover
3. Create hidden wallet and again play with toggle
4. Play with toggle before creating another hidden wallet

![photo_2020-11-05_20-58-50](https://user-images.githubusercontent.com/58593111/98290291-bfa30c80-1fa9-11eb-8f62-1d6e97162143.jpg)
![photo_2020-11-05_20-58-41](https://user-images.githubusercontent.com/58593111/98290307-c467c080-1fa9-11eb-8698-05312a09e4c8.jpg)

**Comment by tsusanka** [comment]
With error in my eyes I have found this issue :). But luckily this seems very edge-casy and I think we can live with that. @wendys-cats can you confirm that Tor works just fine on Windows, just when you "press" a bit you can see these issues?

**Comment by wendys-cats** [comment]
@tsusanka works fine on my Win (produced some [errors](https://github.com/trezor/trezor-suite/issues/2869) again, but it seems to happen strictly within my system and clearing cache + killing trezord fixes it). Managed to produce it once in 15 attempts (with network throttled to 3G).

**Comment by coinhubs** [comment]
I still reproduce this issue in Trezor-Suite-20.12.1-linux-x86_64.AppImage on Ubuntu 20.04.1 LTS
Trezor One in latest firmware

**Comment by prusnak** [comment]
Let's track this in one issue only.
Also this is not limited to OS, it happens at least on WIndows and Linux 

Closed as duplicate of https://github.com/trezor/trezor-suite/issues/3218
