### ISSUE TITLE
After the fw update, the application shows two devices

### ISSUE THREAD

**Issue by zaplmi** [trezor/trezor-suite#4307]
**Describe the bug**
Trezor Suite shows two devices

Few customers has recently reported this sort of an issue in Trezor forum thread:
https://forum.trezor.io/t/info-trezor-stuck-in-bootloader-mode-1-10-0-during-firmware-update/2402/14

After updating from from previous to the latest FW version on MacOS the desktop application shows two devices connected.
After entering passphrase (in order to get into hidden wallet) "Passphrase duplicated" error appears.
(apparently web version of Suite works fine).

Users asked to provide more info (Suite log) if possible. 

**Steps to reproduce:**
1. load standard and passphrase wallet and remember them
2. proceed with firmware update
3.  observe wallet/device selector after update

**Info:**
 - Suite version: 21.9.2 
 - OS: MacOS
 - Device: model Trezor One
 - Bootloader: 1.10.0

**Video:**

https://www.youtube.com/watch?v=g7I4zFb_qUA

**Screenshots:**

<img width="764" alt="obrazek" src="https://user-images.githubusercontent.com/91535734/135098921-9e77eeee-31fd-4347-84d2-6b1e22a29c3a.png">

<img width="710" alt="obrazek2" src="https://user-images.githubusercontent.com/91535734/135098958-f73642d0-e83e-4375-90f9-382161cf5ce3.png">

![obrazek3](https://user-images.githubusercontent.com/91535734/135100635-550d964a-5a1b-42a9-bf00-5b0e80bbee30.jpeg)

**Comment by bosomt** [comment]
i was able to reproduce issue /see my video in issue/ on my macOS M1.
And I was not able to reproduce issue with KUbuntu linux
Issue occurs when you use old 2.0.27 and new 2.0.31 versions of Trezor Bridge.

**Comment by bosomt** [comment]
Latest info from customer :
https://forum.trezor.io/t/info-trezor-stuck-in-bootloader-mode-1-10-0-during-firmware-update/2402/15
I ended with same result, I'm not able to access my Suite any more. Doesn't matter if i have connected device or not it shows this: 

<img width="784" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/135210687-03d39e34-e441-4c97-9072-21738218b6bf.png">

Maybe we should again consider to add delete storage button to Welcome screen as it was planned during initial development.

**Comment by jerechinsky** [comment]
@matejkriz do you think it's feasible to try to fix this issue or should I request that product team considers the "delete storage" button per Bošo's tip?

**Comment by matejkriz** [comment]
@alex-jerechinsky I believe it's worth a try to fix it.

BTW, we should fix the referenced issue https://forum.trezor.io/t/info-trezor-stuck-in-bootloader-mode-1-10-0-during-firmware-update/2402  too! It is this issue: https://github.com/trezor/trezor-suite/issues/4132 (not related to two devices after update, but to intermediary...)

**Comment by tsusanka** [comment]
@bosomt please retest.

**Comment by bosomt** [comment]
**QA NOK**

@tsusanka issue is still present in current dev master. I was able to reproduce it with model One and not with model T.
I think that issue is related to reboot to bootloader ability of model One. it's never reconnected during fw update.

<img width="725" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/137931117-8b0f3c0c-1839-47b3-aa57-9e8468c73bfb.png">


**Info:**
 - Suite version: desktop 21.11.0 (60ba7ae6f1eea65dfa8692bff0cb3cf9dbcea977)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.11.0 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.3 regular

**Comment by mroz22** [comment]
Hmm this is not happening on my machine. Looks like we will need @tomasklim again to debug this :( sorryy :sob:

**Comment by jerechinsky** [comment]
@tomasklim will try to replicate on his machine.

**Comment by tomasklim** [comment]
@mroz22 ez
<img width="446" alt="Screenshot 2021-10-22 at 13 47 54" src="https://user-images.githubusercontent.com/33235762/138449494-9caaef2d-9156-406d-adcc-766be22a53f5.png">
<img width="769" alt="Screenshot 2021-10-22 at 13 47 30" src="https://user-images.githubusercontent.com/33235762/138449499-d0415095-8b0b-4741-b720-2af1c418982a.png">

It makes app unusable and you have to reset it.

**Comment by tomasklim** [comment]
Info:
This issue happens only on `macOS` both in `web` and `desktop` app. It does not matter if `webUSB` or `Bridge` is used.

The problem is following:

1. Remembered devices are stored in Redux state in `devices`
2. On `non-macOS` devices, when device is reconnected into `bootloader`, `device-disconnect` event is fired, which makes remembered devices disconnected. However, on `macOS` this does not happen. 
3. On `non-macOS` devices, `device-connect` is fired and it connects a new device in bootloader. However, on `macOS` this does not happen. 
4. On `macOS` the remembered devices remain connected, so method `changeDevice` in `deviceReducer.ts` on event `device-changed` change remembered devices into bootloader mode (line 144) and those remembered devices in bootloader mode cause the problems.
5. When device is successfully updated `device-disconnect` and `device-connect` is fired on all OS including `macOS`

The problem is related to #4233 which was fixed by https://github.com/trezor/connect/commit/981958717e7e50f0bf4dd51d453c2dce2243f31a

**Comment by bosomt** [comment]
**QA OK**

**Info:**
 - Suite version: web 21.12.0 (d37ce6043f3285ec3ef09901859607275c24ac84)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:94.0) Gecko/20100101 Firefox/94.0
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model 1 1.10.3 regular
