### ISSUE TITLE
Missing Czech translations

### ISSUE THREAD

**Issue by bosomt** [trezor/trezor-suite#4338]
**Describe the bug**
Found some English sentences that are not translated.

**Info:**
 - Suite version: desktop 21.10.1 (ea82dd4a00ad06e3c36a267be1c08ade554dac58)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/21.10.1 Chrome/93.0.4577.58 Electron/14.0.0 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.4.2 regular

**Screenshots:**

1) Enter passphrase on device

<img width="399" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/136097921-82425f4d-c79d-4737-9835-b1ecd73ea7b5.png">

2) new wallet is called new wallet in notifications even wallet name is in Czech language

![obrazek](https://user-images.githubusercontent.com/31506317/136098128-7d24df26-862a-437b-ae22-308680a85bbc.png)

3) Graph 

![obrazek](https://user-images.githubusercontent.com/31506317/136098188-060af47f-b25c-49be-a3d0-8b24dfc5b1a1.png)

![obrazek](https://user-images.githubusercontent.com/31506317/136098229-9d56e391-bda6-4e23-b07e-3f82996d0d83.png)

4) Creating new wallet 

![obrazek](https://user-images.githubusercontent.com/31506317/136098329-9ec9c232-3f2b-4dbc-b054-c1d4b1c82ab7.png)

5) Working in Settings/Crypto sounds strange

`Nastavení mincí také definuje, která síť bude objevena po připojení vašeho Trezoru.`

**Comment by STew790** [comment]
So far I found these that are not translated (will edit as I found other ones):

**6.** "Search" in Accounts section:
![image](https://user-images.githubusercontent.com/48477147/136222023-1c845c51-ca81-4061-89c8-8946840f77f7.png)

**7.** "All" in Account, under the graph.
![image](https://user-images.githubusercontent.com/48477147/136223098-04a2e545-14c2-46b4-a811-c4ae686286b6.png)

**8.** "Sent"/"Received" in the transactions
![image](https://user-images.githubusercontent.com/48477147/136223524-eec4cc9d-088d-4437-8e53-f5e2f56f92bc.png)

**9.** Not really sure about this one, the fee for transactions
![image](https://user-images.githubusercontent.com/48477147/136225117-c6df3f5a-a0cb-4815-8e01-64c99e6dcfe8.png)

**10.** When you hover over your wallet it says "Connected" but in the select wallet modal it correctly states "Připojeno"
![image](https://user-images.githubusercontent.com/48477147/136225968-754e0c1c-2149-46e5-bcc5-55b9a57f4f0a.png)

**11.** Sign and Verify "Address" select
![image](https://user-images.githubusercontent.com/48477147/136228335-24ea8fed-a7af-4fc6-bde5-c019100772f4.png)

**12.** Auto-lock time settings
![image](https://user-images.githubusercontent.com/48477147/136229339-46dd9be0-82de-4418-adcf-b90140a86f82.png)

**13.** Here should be "nebo" before the 33 since there is a "buď" in the Recovery seed check modal
![image](https://user-images.githubusercontent.com/48477147/136231611-c8be579a-4caf-4b7c-866c-97c766606a97.png)

**Comment by jerechinsky** [comment]
**14.**


1st troubleshooting step on "connect your trezor" screen

![Screenshot 2021-10-06 at 16 03 47](https://user-images.githubusercontent.com/75733878/136222279-07685f52-033d-455a-b435-f656ef343d1b.png)

**Comment by bosomt** [comment]
**15.**
I'm not sure if it's expected or not.
But . appeared in Czech version of suite :)

<img width="305" alt="Screenshot 2021-10-06 at 19 49 59" src="https://user-images.githubusercontent.com/31506317/136257027-5eb353ec-b7fb-4156-bbe2-8f28b8c4445c.png">
<img width="243" alt="Screenshot 2021-10-06 at 19 50 15" src="https://user-images.githubusercontent.com/31506317/136257020-bb7bed0e-3f4f-473c-85b0-f68635ffd878.png">

**Comment by bosomt** [comment]
**16.**
it suppose to say 13 minci and not 13 mince

<img width="505" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/136261332-422c4a14-5508-4677-bfcc-175cd305b301.png">

**Comment by wendys-cats** [comment]
**17.**
Error: Device call in progress - English should not be present
![image](https://user-images.githubusercontent.com/58593111/136268008-8ea0db13-af90-44b8-8a62-4f6b6d4832e4.png)

**Comment by wendys-cats** [comment]
**18.**
Error: Pin entry cancelled - English should be not present
![image](https://user-images.githubusercontent.com/58593111/136272725-4b389549-4da3-46a3-aa84-5170cf7b95d3.png)

**Comment by wendys-cats** [comment]
**19.**
Error message in Dashboard: incorrect message (entering passphrase was cancelled, not PIN)
![image](https://user-images.githubusercontent.com/58593111/136277039-23cb0fdf-af26-414b-a7ec-0761351d7f7e.png)

**Comment by wendys-cats** [comment]
**20.**
English should not be present.
![image](https://user-images.githubusercontent.com/58593111/136362911-9a18ca36-d66e-478f-950e-983d09e94d33.png)

**Comment by bosomt** [comment]
**21.**
Czech vs English hint in wallet selector modal

<img width="318" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/136366183-49151432-6c38-4d9d-b785-0c6a8fb2e914.png">

<img width="299" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/136366213-18cd5cbc-42dc-490f-93a9-0631b9210159.png">

**Comment by wendys-cats** [comment]
**22.**
Sign and Verify - placeholder for address dropdown is in English
![image](https://user-images.githubusercontent.com/58593111/136368410-8634f72b-91b4-4eb6-821a-b8b8d0f4bc9a.png)

**Comment by tomasklim** [comment]
Fixed in https://github.com/trezor/trezor-suite/pull/4348 (new strings are not yet translated into Czech/Spanish, but in debug mode it should have green border)

| № | status |
| ------------- | ------------- |
| [**1 - 4**](https://github.com/trezor/trezor-suite/issues/4338#issue-1016798481)| ✅ fixed |
| [**5**](https://github.com/trezor/trezor-suite/issues/4338#issue-1016798481) | needs to be modified in crowdin |
| [**6 - 12**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-936329520) | ✅ fixed |
| [**13**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-936329520) | needs to be modified in crowdin |
| [**14**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-936332298) | ✅ fixed |
| [**15**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-936789966) | needs to be modified in crowdin, I think `Verze aplikace` is the string we are looking for |
| [**16**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-936847324) | not sure how we want to deal with this |
| [**17**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-936940300) | string from `connect` |
| [**18**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-936998783) | string from `connect` |
| [**19**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-937055802) | needs to be modified in crowdin |
| [**20**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-937640028) | string from `connect` |
| [**21**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-937656526) | needs to be modified in crowdin |
| [**22**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-937667815) | ✅ fixed |

**Comment by bosomt** [comment]
**23.** 
Enable labelling is translated as Popisky povoleny, correct translation should be Povolení popisků" nebo "Zapnutí popisků" 

![obrazek](https://user-images.githubusercontent.com/31506317/136377410-f6ace173-9342-4058-a78f-61be0e3932ef.png)

**Comment by wendys-cats** [comment]
**24.**
Translation is OK, but alignment is a bit wonky
![image (2)](https://user-images.githubusercontent.com/58593111/136386706-d020f1ce-4f37-40c6-969c-942590df1cad.png)

**Comment by wendys-cats** [comment]
**25.**

Exchange - English should not be present.
![image](https://user-images.githubusercontent.com/58593111/136388880-de13bfea-d0aa-4a4f-9aa8-3efae7c1f646.png)

**26.**
Sell - English should not be present.
![image](https://user-images.githubusercontent.com/58593111/136389068-fbc3f42a-960b-4a58-8075-afc826f66c97.png)

**27.**
Buy - wouldn't something like "Způsoby platby" be better than "Zaplaceno" ?
![image](https://user-images.githubusercontent.com/58593111/136389215-4221f12a-64ad-40cf-ac65-b21bb2f1d85e.png)

**Comment by wendys-cats** [comment]
**28.**
Wallet modal - long Czech translation moves the labeling icon and it is really cropped 
![image](https://user-images.githubusercontent.com/58593111/136389566-37ab78dc-a95b-40ea-8139-f9bdad68ebba.png)

**Comment by wendys-cats** [comment]
**29.**
Exchange and Buy - "Receive address" translation is incorrect and inconsistent (see exchange vs receive)

Exchange/Buy
![image](https://user-images.githubusercontent.com/58593111/136390363-0bd75a60-96b1-4553-96cf-0c5e00d763c0.png)
**30.**
Receive - action in Account that shows your next unused receive address
![image](https://user-images.githubusercontent.com/58593111/136390691-fa76b2a6-ffda-46ac-8c20-7fcb6dab1135.png)

**Comment by jerechinsky** [comment]
I numbered everything so we can reference everything more easily. Especially during re-testing.

Most of the following changes will apply after we sync Crowdin with Suite. I will let you know.

| №  | status |
| ------------- | ------------- |
|[**5**](https://github.com/trezor/trezor-suite/issues/4338#issue-1016798481)| ✅ Fixed. New copy:`Nastavení kryptoměn také určuje, jak Trezor Suite provede proces zjišťování kryptoměn pokaždé, když připojíte zařízení, které není zapamatované.` |
|[**13**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-936329520)|✅ Fixed by adding `nebo`.|
| [**15**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-936789966) |✅ Fixed. Changed to `Verze aplikace` and removed the period.|
|[**16**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-936847324)|🚫 This requires a custom plural form for Czech language in Crowdin. Will create a follow-up issue.|
|[**19**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-937055802)|✅ Fixed. New copy: `Je nám líto, ale autorizační proces selhal. Zmáčkněte prosím "Opakovat" nebo odpojte a přípojte své zařízení.`|
|[**21**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-937656526)|✅ Fixed. New copy: `Smaže veškeré informace o vaší peněžence z aplikace.`|
|[**23**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-937713044)|✅ Fixed. New copy: `Popisky`.|
|[**25**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-937770706)|🚫 Missing in crowdin.|
|[**26**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-937770706)|🚫 Missing in crowdin.|
|[**27**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-937770706)|✅ Fixed. New copy:`Způsoby platby`.|
|[**28**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-937772828)|✅🤞The copy has been since changed to `Standardní peněženka`, which is shorter, so hopefully that'll fix it.|
|[**29**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-937781633)|✅ Fixed. New copy: `Přijímací adresa`. 
|[**30**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-937781633)|❗️ I left it as is. I believe this copy suits better there and inconsistency isn't a big deal here IMO.

**So we have yet to fix:** 

| №  | what's wrong |
| ------------- | ------------- |
|[**16**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-936847324)|custom plural form to create|
| [**17**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-936940300) | string from `connect` |
| [**18**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-936998783) | string from `connect` |
| [**20**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-937640028) | string from `connect` |
|[**25**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-937758254)|wonky alignment|
|[**25**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-937770706)|missing in crowdin|
|[**26**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-937770706)|missing in crowdin|

**Comment by wendys-cats** [comment]
**31.**
Safety Check Promts - shouldn't "Kompletní zabezpečení Trezor." be something like "Kompletní zabezpečení zařízení Trezor." ? 

![image](https://user-images.githubusercontent.com/58593111/136566297-b38649c1-f025-4e13-a09a-bbdd3230295b.png)

**Comment by bosomt** [comment]
**32.**
`Your address is where you'll receive your ETH.`
vs
`= obdržíte svůj ETH na tuto adresu` 
:)
 
<img width="585" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/136567282-4749a278-595f-4ed7-8280-087aaed4d77e.png">

![obrazek](https://user-images.githubusercontent.com/31506317/136567311-21a2b748-7734-407a-99ba-6758b7f9bdf1.png)

**Comment by bosomt** [comment]
**33.**
Current: `Odesláno z`
Correct: `Odeslat z`

<img width="543" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/136568459-7e70b44c-d465-406d-a410-628adf229b92.png">

**Comment by bosomt** [comment]
**34.**
Invity modal in Exchanges is missing some information.

<img width="429" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/136586021-fbbfbb8a-9d2d-4e63-a003-88d13e16070f.png">

**Comment by jerechinsky** [comment]
| №  | status |
| ------------- | ------------- |
|[**31.**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-938647947)| ✅ Fixed. New copy:`Kompletní zabezpečení Trezoru.` |
|[**32.**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-938652556)| ✅ Fixed. New copy:`Svůj {symbol} obdržíte na svoji adresu.` |
|[**33.**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-938658445)| ✅ Fixed. New copy:`Odeslat z`. |
|[**34.**](https://github.com/trezor/trezor-suite/issues/4338#issuecomment-938647947)| ✅ First string fixed. New copy:`Invity je porovnávací nástroj, který vám doporučí ty nejlepší směnárny. Použijí jen vaši polohu, aby vám ukázali ty nejrelevantnější nabídky.`<br /> Original copy in english is `Invity is a comparison tool that connects you to the best exchange providers. They only use location in order to show the most relevant offers.`<br /><br />✅ Second string fixed. New copy:`Invity nevidí žádné vaše údaje o platbě nebo KYC; tyto údaje sdílíte pouze se směnárnou, pokud se rozhodnete využít její služeb.`<br />Original copy in english is `Invity does not see any of your payment or KYC information; you share this only with the exchange provider if you choose to finish the transaction.`|

**Comment by bosomt** [comment]
Device recovery is has broken text/link. 
It says `{TR_LEARN_MORE}` at end.

+edit: maybe we can consider changing names of recovery to Zakladni and Pokrocile, it looks strange with lower case

![obrazek](https://user-images.githubusercontent.com/31506317/136904848-586b35b3-0bd2-414d-9f68-bf61039effb8.png)

**Comment by tomasklim** [comment]
> Device recovery is has broken text/link. It says `{TR_LEARN_MORE}` at end.
> 
> +edit: maybe we can consider changing names of recovery to Zakladni and Pokrocile, it looks strange with lower case
> 
> ![obrazek](https://user-images.githubusercontent.com/31506317/136904848-586b35b3-0bd2-414d-9f68-bf61039effb8.png)

Both problems are in crowdin. 

Btw. e.g. `TR_BASIC_RECOVERY` has `\n` in English text but in Czech text it is not there (It is required in neither of them). I think, we should get rid of `\n` as much as possible to avoid future inconsistencies between languages.

**Comment by jerechinsky** [comment]
I think most of these should be fixed now as copy has been updated. It's also been cherry-picked onto staging. I think there's no need to re-test every single thing. I've only confirmed that **28.** got fixed since I wasn't sure about that one and it looks good on my end!

![Screenshot 2021-10-12 at 19 01 56](https://user-images.githubusercontent.com/75733878/136998924-7ceb953c-40b1-4597-8a42-3bd5dac8dc42.png)
![Screenshot 2021-10-12 at 19 02 12](https://user-images.githubusercontent.com/75733878/136998929-9d6e1bf9-0d79-4fda-879a-881ecbfc0880.png)

**Comment by bosomt** [comment]
this is how disco-very error looks like in Czech , looks confusing to me.

`Chyba při detekci.
Popis chyby při zjišťování`

<img width="793" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/137088547-b1dc32b2-46f8-4c63-912f-0b62109f2443.png">

**Comment by STew790** [comment]
Unfortunately, [4](https://github.com/trezor/trezor-suite/issues/4338#issue-1016798481) is still not fixed.
Staging version web 21.10.1 (aa3adfa347d0416f970a7fae720d3350f29f8916)

edit:
My bad, I didn't realize this fix wasn't on staging yet. Disregard, please.

![image](https://user-images.githubusercontent.com/48477147/137109527-6b6c4039-5192-4145-8c71-d60205b19fef.png)

**Comment by jerechinsky** [comment]
Tom's fixes in #4348 didn't make it in this release, so I'll leave this in the November project, because they still need QA approval for next release.

**Comment by bosomt** [comment]
Drop image should not be translated to Pustit obrazek, correct translation is probably Zmazat/zahodit/odstranit obrazek.

<img width="785" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/138440247-e13e533c-21a1-4b05-83d2-5de62caa7d59.png">

**Comment by tomasklim** [comment]
`Powered by` is not translated in Crowdin
![Screenshot 2021-10-25 at 20 31 38](https://user-images.githubusercontent.com/33235762/138750538-4e67d3f9-d093-4e44-94c1-747a3618134d.png)

**Comment by tomasklim** [comment]
25. and 26. cannot be translated in code. The string are coming from INVITY AP
![Screenshot 2021-10-25 at 20 49 18](https://user-images.githubusercontent.com/33235762/138752966-86239597-a59c-483d-b05e-a4a8f9bad702.png)
![Screenshot 2021-10-25 at 20 33 58](https://user-images.githubusercontent.com/33235762/138752973-cd95513a-80f3-4da8-806f-ef3b243fd2ad.png)
I.

**Comment by bosomt** [comment]
I just found incorrect text strings. See screenshot, same device same step during onboarding.
Different wording `Advanced recovery` vs `Šamirova záloha` but with same results. Advanced recovery is started.
It would be great to fix it in next Suite release /i was able to reproduce is issue in 21.10.2 and 21.11.0 versions of Suite/


<img width="913" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/138914569-f68123e3-58b5-4124-9684-62cdfa4232c9.png">

<img width="936" alt="obrazek" src="https://user-images.githubusercontent.com/31506317/138915051-c31df3ff-ad1e-4b63-9e61-ef888a5ec808.png">

**Comment by bosomt** [comment]
`Advanced recovery / Šamirova záloha` translation fixed in https://github.com/trezor/trezor-suite/issues/4524

**Comment by bosomt** [comment]
@alex-jerechinsky 

i just found multiple issues in Czech version of 21.12.1 version of suite

**1) missing string {walletLabel}  again**
<img width="243" alt="Screenshot 2021-12-01 at 9 08 10" src="https://user-images.githubusercontent.com/31506317/144199327-b9a5aa82-4adf-480d-aeee-382965f1558f.png">

**2) In transaction hsitory I see `Přijmout` but in transaction detail it's `Přijato`**
<img width="330" alt="Screenshot 2021-12-01 at 9 26 00" src="https://user-images.githubusercontent.com/31506317/144199335-b456ff4c-8364-49b4-af4e-79d52bbc0820.png">


**3) in account types you can see Segwit mentioned two times.**
<img width="279" alt="Screenshot 2021-12-01 at 9 27 30" src="https://user-images.githubusercontent.com/31506317/144199342-c9d703ea-93a3-48b6-a886-271dc9a05781.png">
<img width="280" alt="Screenshot 2021-12-01 at 9 28 25" src="https://user-images.githubusercontent.com/31506317/144199347-b494e846-e28f-4c23-94cb-0741a77b0838.png">

**Comment by bosomt** [comment]
https://github.com/trezor/trezor-suite/issues/4338#issuecomment-983410767 
3)  Incorrect Czech translation of legacy account names 
fixed in
https://github.com/trezor/trezor-suite/issues/4697#issuecomment-1010309129

**Comment by jerechinsky** [comment]
everything should be fixed except `Powered by invity` and 25. and 26.
