### ISSUE TITLE
Older transaction popping up at the top of the tx export list

### ISSUE THREAD

**Issue by wendys-cats** [trezor/trezor-suite#5718]
**Describe the bug**
Suite will in some case place older transactions among the latest in export list. It does not happen consistently, there seems to be no particular trigger that can replicate this every time. First seen last month (3rd June). Suspecting pending transactions (together with labeling?) in export mix up the order. **Clearing app cache (with Reset app button in Settings) gets rid of the issue.** 

**Info:**
 - Suite version: desktop 22.6.4 (5fc4cec20d2b691634e695f7547cb955cff22171), but also 
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.6.4 Chrome/94.0.4606.81 Electron/15.3.0 Safari/537.36
 - OS: Win32
 - Screen: 1920x1080
 - Device: model T 2.5.1 regular (revision 85a26d2c9593bcdf858c2d718d79951ca927a0c3)
 - Transport: bridge 2.0.31
 - Connection: custom to default Trezor btc1 blockbook
 

**How to reproduce**

1. Download tx export with labeling enabled
2. See misplaced transactions in the list

**Expected behavior**
Correct sorting (latest to oldest)

**Screenshots**
These exports are only minutes apart, same account, same labeliling (local)
![image](https://user-images.githubusercontent.com/58593111/176616656-ecb99e6c-da4c-4816-a915-ad674b294ef6.png)

Export of the same account, circa 15mins after. Labeling is not enabled.
![image](https://user-images.githubusercontent.com/58593111/176617669-fd480039-7c4b-4554-a074-1cbe9ec09dbc.png)

Local labeling enabled (after switching from first Google, the to Dropbox, to Local last
![image](https://user-images.githubusercontent.com/58593111/176619155-ab927bd3-a6b9-43d8-a3b6-d561701c198c.png)

**Comment by bosomt** [comment]
**QA OK**

fixed in new export 

**Info:**
 - Suite version: desktop 22.9.3 (2b9595fdfee9d36935d72af4af536d2fe4742f5e)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/22.9.3 Chrome/100.0.4896.160 Electron/18.3.5 Safari/537.36
 - OS: MacIntel
 - Screen: 1680x1050
 - Device: model T 2.5.3 Universal (revision 9cec8f057a28afb2f6d432cc90c0a586833b6670)
 - Transport: bridge 2.0.32

**Comment by MatthewDavid1984** [comment]
This happened to me today while testing exports on windows desktop suite. I had two pending (incoming) transactions and labeling was disabled. Edit: Resetting the app has cleared up the issue even though the transactions are still pending.

 - Suite version: desktop 23.2.1 (d76d623f65060a6727f84e34c3e65e515c22b2f1)
 - Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuite/23.2.1 Chrome/104.0.5112.124 Electron/20.3.5 Safari/537.36
 - OS: Win32
 - Screen: 1366x768
 - Device: model T 2.5.3 Universal (revision 2f03ace311584988d5aeab58fd1acf24ef54711a)
 - Transport: BridgeTransport 2.0.27

[Bitcoin_1_20230201T175642.pdf](https://github.com/trezor/trezor-suite/files/10557867/Bitcoin_1_20230201T175642.pdf)

**Comment by MatthewDavid1984** [comment]
Still happening on 23.3.2 (2ab6b568), Win32, TT firmware 2.5.3 universal

**Comment by sime** [comment]
@MatthewDavid1984 did you find a way to consistently reproduce this? Need to find an example before attempting to fix it.

**Comment by MatthewDavid1984** [comment]
@sime afraid not, just tried exporting to pdf on 23.4.1 with 4 txs pending and everything looks fine. i'll let you know if i encounter it again

**Comment by MatthewDavid1984** [comment]
[Bitcoin_1_20230405T095610.csv](https://github.com/trezor/trezor-suite/files/11155658/Bitcoin_1_20230405T095610.csv)
@sime i spoke too soon, the csv is messed up but the pdf is fine. but that still doesn't make for a consistent reproduction necessarily, all i can say is have multiple pending transactions in the usual testing wallet and then export.

**Comment by sime** [comment]
@MatthewDavid1984 and the pending TXs appear in the output?

I'd tempted to remove them from the CSV as pending and TXs shouldn't be trusted.

**Comment by MatthewDavid1984** [comment]
yes, pending transactions appear

**Comment by bosomt** [comment]
**QA NOK**


pending transactions are already removed but i can see older transactions at top of tx history 🤷🏿 
I hope it will get fixed in https://github.com/trezor/trezor-suite/issues/8013

![image](https://github.com/trezor/trezor-suite/assets/31506317/752bb1b4-21c4-4f30-acf2-f892c1855a17)

<img width="211" alt="image" src="https://github.com/trezor/trezor-suite/assets/31506317/cd294f93-2318-4a05-8119-a4a5f59c1f41">



**Info:**
 - Suite version: desktop 23.7.0 (d81e7e2a7c127bc4e494b69375831cd4b0998bd8)
 - Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) TrezorSuiteDev/23.7.0 Chrome/112.0.5615.204 Electron/24.5.1 Safari/537.36
 - OS: MacIntel
 - Screen: 1440x900
 - Device: model T 2.6.1 Universal (revision c3f6e8f19fd647c73b414322e287ba23cf8a0c7c)
 - Transport: NodeUsbTransport

**Comment by EuryShadow** [comment]
**QA OK**

The issue did not occur on seven different exports. Feel free to reopen if it happens again.

**Info:**
 - Suite version: desktop 25.10.2 (b6bcf7f586b0d5c6da2b3630f726500566e56697)
 - Browser: Trezor Suite 25.10.2
 - OS: MacIntel
 - Screen: 1710x1112
 - Device: Trezor T3W1 2.9.3 universal (revision 0bd923c78990d8d58f82fe18660e57399aafc0f1)
 - Transport: BridgeTransport 3.1.0, BluetoothTransport
